[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.curl", "php83Extensions.xml", "php83Extensions.zip", "nodejs_20", "npm"]

[phases.install]
cmds = ["composer install --no-interaction --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"